local:
  dialect: postgres
  datasource: dbname=classifier-aas user=db password=db sslmode=disable port=228
  dir: migrations
  table: sqlmigrate-migrations

develop:
  dialect: postgres
  datasource: host=3.121.253.22 dbname=classifier-aas user=db password=db sslmode=disable port=228
  dir: migrations
  table: sqlmigrate-migrations