version: '3.7'

services:
  app:
    build: .
    restart: always
    ports:
      - "227:8000"
      - "229:9000"
    networks:
      default: null
    depends_on:
      - pg
  pg:
    image: postgres:16
    restart: always
    ports:
      - "228:5432"
    volumes:
      - classifier-aas-postgres-data:/var/lib/postgresql/data
      - ./scripts/db/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql:ro
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=classifier-aas
    networks:
      default: null

volumes:
  classifier-aas-postgres-data: {}

networks:
  default:
    external: true
    name: classifier