version: '3.7'

services:
  pg:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql:ro
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    networks:
      - classifier-aas

volumes:
  postgres-data: {}

networks:
  classifier-aas: