version: '3.7'

services:
  pg:
    image: postgres:16
    restart: always
    ports:
      - "228:5432"
    volumes:
      - classifier-aas-postgres-data:/var/lib/postgresql/data
      - ./scripts/db/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql:ro
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=classifier-aas
    networks:
      - classifier-aas-net

volumes:
  classifier-aas-postgres-data: {}

networks:
  classifier-aas-net: